version: "3.8"
services:
  grafana:
    image: grafana/grafana:8.3.4
    environment: 
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=ngalert
      - GF_INSTALL_PLUGINS=https://github.com/denniskniep/grafana-datasource-plugin-neo4j/releases/download/v1.1.0/kniepdennis-neo4j-datasource-1.1.0.zip;kniepdennis-neo4j-datasource
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000

  neo4j:
    image: neo4j:4.4.3
    environment:
      #- NEO4J_AUTH=none   
      - NEO4J_AUTH=neo4j/Password123
      - NEO4JLABS_PLUGINS=["apoc"] 
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687

  neo4j-provisioning:
    image: neo4j:4.4.3 
    volumes:
      - ./neo4j/initMovieDb.cql:/initMovieDb.cql
      - ./neo4j/wait-for.sh:/wait-for.sh
    entrypoint: []
    command: /bin/sh -c '/wait-for.sh http://neo4j:7474 -- cypher-shell -a neo4j://neo4j:7687 -u neo4j -p Password123 -f /initMovieDb.cql'
    

volumes:
  neo4j-data:      
